var path = require('path');
var webpack = require('webpack');

module.exports = {
	context: path.resolve('js'),
	entry: ["./app"],
	output: {
		path: path.resolve('build/js'),
		publicPath: '/public/assets/js',
		filename: "bundle.js"
	},


	devServer: {
		contentBase: 'public'
	},

	module: {
		loaders: [
			{
				test: /\.js$/,
				exclude: /node_modules/,
				loader: "babel-loader"
			},
			{
				test: /\.scss$/,
				exclude: /node_modules/,
				loader: "style-loader!css-loader!autoprefixer-loader!sass-loader"
			},
			{
				test: /\.(png|jpg|ttf|eot)$/,
				exclude: /node_modules/,
				loader: "url-loader?limit=100000"
			}
		]
	},

	plugins: [
		new webpack.optimize.CommonsChunkPlugin('shared.js'),
		new webpack.BannerPlugin("++++ GENERATED BY WEBPACK BANNER PLUGIN +++++++")
	],

	resolve: {
		extensions: ['','.js']
	}
}